Require go
Output ./_examples/recordings/v0.gif

Set Shell zsh
Set FontSize 12
Set Width 440
Set Height 430
Set Padding 10
Set WindowBar Colorful

Type "go run ./cmd -bot impossible"
Enter
Sleep 3s

Set TypingSpeed 100ms

# 0 0
Space
Sleep 500ms

# 0 2
Down 2
Space
Sleep 500ms

# 2 1
Up
Right 2
Space
Sleep 500ms

# 1 2
Left
Down
Space
Sleep 500ms

# 1 0
Up 2
Space
Sleep 500ms

# 2 0
Right
Space
Sleep 3s
